from fastapi import FastAPI

app = FastAPI(title="JIC Projects Mock API", version="1.0.0")


PROJECTS = [
    {
        "id": 1,
        "titulo": "Sistema de monitoreo ambiental con IoT",
        "ano": "2025",
        "universidad": "Universidad Tecnologica de Panama",
        "siglas": "UTP",
        "resumen": "Desarrollo de sensores IoT para medir calidad del aire y emitir alertas tempranas en tiempo real.",
        "categoria": "Ingenieria",
        "premio": "Primer Lugar",
        "asesor": "Carlos Mendoza",
        "email": "carlos.mendoza@utp.ac.pa",
        "institucion": "Facultad de Ingenieria Electrica",
        "activo": 1,
    },
    {
        "id": 2,
        "titulo": "Gemelo digital para mantenimiento predictivo industrial",
      "ano": "2025",
        "universidad": "Universidad de Panama",
        "siglas": "UP",
        "resumen": "Plataforma de analitica para anticipar fallas en maquinaria critica mediante series temporales.",
        "categoria": "Ingenieria",
        "premio": "Segundo Lugar",
        "asesor": "Maria Garcia",
        "email": "maria.garcia@up.ac.pa",
        "institucion": "Facultad de Ingenieria",
        "activo": 1,
    },
    {
        "id": 3,
        "titulo": "Materiales biodegradables con residuos agricolas",
      "ano": "2025",
        "universidad": "Universidad Autonoma de Chiriqui",
        "siglas": "UNACHI",
        "resumen": "Creacion de biopolimeros para empaques sostenibles aprovechando subproductos agroindustriales.",
        "categoria": "Ingenieria",
        "premio": "Tercer Lugar",
        "asesor": "Diana Herrera",
        "email": "diana.herrera@unachi.ac.pa",
        "institucion": "Laboratorio de Innovacion Sostenible",
        "activo": 1,
    },
    {
        "id": 4,
        "titulo": "Analisis de biomarcadores en diabetes tipo 2",
        "ano": "2025",
        "universidad": "Universidad Latina de Panama",
        "siglas": "ULAT",
        "resumen": "Estudio de biomarcadores clinicos asociados a progresion de diabetes tipo 2 en poblacion universitaria.",
        "categoria": "Ciencias de la Salud",
        "premio": "Primer Lugar",
        "asesor": "Roberto Castillo",
        "email": "roberto.castillo@ulatina.edu.pa",
        "institucion": "Facultad de Medicina",
        "activo": 1,
    },
    {
        "id": 5,
        "titulo": "Prediccion de brotes de dengue con ML",
      "ano": "2025",
        "universidad": "Universidad Catolica Santa Maria La Antigua",
        "siglas": "USMA",
        "resumen": "Modelo predictivo con datos climaticos y epidemiologicos para apoyar decisiones de salud publica.",
        "categoria": "Ciencias de la Salud",
        "premio": "Segundo Lugar",
        "asesor": "Fernando Morales",
        "email": "fernando.morales@usma.ac.pa",
        "institucion": "Centro de Analitica en Salud",
        "activo": 1,
    },
    {
        "id": 6,
        "titulo": "Plantas medicinales con actividad antiinflamatoria",
      "ano": "2025",
        "universidad": "Universidad Especializada de las Americas",
        "siglas": "UDELAS",
        "resumen": "Caracterizacion fitoquimica y pruebas in vitro de especies nativas con potencial terapeutico.",
        "categoria": "Ciencias de la Salud",
        "premio": "Tercer Lugar",
        "asesor": "Patricia Solis",
        "email": "patricia.solis@udelas.ac.pa",
        "institucion": "Instituto de Investigacion Biomedica",
        "activo": 1,
    },
    {
        "id": 7,
        "titulo": "Catalogo de biodiversidad con teledeteccion",
        "ano": "2025",
        "universidad": "Universidad Interamericana de Panama",
        "siglas": "UIP",
        "resumen": "Clasificacion de cobertura vegetal usando imagenes satelitales y aprendizaje supervisado.",
        "categoria": "Ciencias Naturales y Exactas",
        "premio": "Primer Lugar",
        "asesor": "Luis Ramirez",
        "email": "luis.ramirez@uip.edu.pa",
        "institucion": "Laboratorio de Geomatica Aplicada",
        "activo": 1,
    },
    {
        "id": 8,
        "titulo": "Modelado matematico de ecosistemas costeros",
      "ano": "2025",
        "universidad": "Universidad Maritima Internacional de Panama",
        "siglas": "UMIP",
        "resumen": "Modelo de dinamica poblacional para analizar resiliencia de ecosistemas costeros del Pacifico panameno.",
        "categoria": "Ciencias Naturales y Exactas",
        "premio": "Segundo Lugar",
        "asesor": "Ana Prado",
        "email": "ana.prado@umip.ac.pa",
        "institucion": "Centro de Investigacion Ambiental",
        "activo": 1,
    },
    {
        "id": 9,
        "titulo": "Monitoreo de arrecifes con aprendizaje profundo",
      "ano": "2025",
        "universidad": "Universidad Tecnologica OTEIMA",
        "siglas": "OTEIMA",
        "resumen": "Deteccion automatica de blanqueamiento coralino mediante vision computacional en imagenes submarinas.",
        "categoria": "Ciencias Naturales y Exactas",
        "premio": "Tercer Lugar",
        "asesor": "Jorge Castillo",
        "email": "jorge.castillo@oteima.ac.pa",
        "institucion": "Unidad de Ciencia Marina",
        "activo": 1,
    },
    {
        "id": 10,
        "titulo": "Estrategias de inclusion digital en escuelas",
        "ano": "2025",
        "universidad": "Universidad Metropolitana de Educacion Ciencia y Tecnologia",
        "siglas": "UMECIT",
        "resumen": "Evaluacion de programas de alfabetizacion digital en zonas rurales y su impacto academico.",
        "categoria": "Ciencias Sociales y Humanisticas",
        "premio": "Primer Lugar",
        "asesor": "Paola Rivera",
        "email": "paola.rivera@umecit.edu.pa",
        "institucion": "Observatorio de Innovacion Educativa",
        "activo": 1,
    },
    {
        "id": 11,
        "titulo": "Impacto socioeconomico de la migracion rural",
      "ano": "2025",
        "universidad": "Universidad del Istmo",
        "siglas": "UDI",
        "resumen": "Investigacion mixta sobre empleo, movilidad y acceso a servicios en comunidades rurales vulnerables.",
        "categoria": "Ciencias Sociales y Humanisticas",
        "premio": "Segundo Lugar",
        "asesor": "Rosa Pineda",
        "email": "rosa.pineda@udi.edu.pa",
        "institucion": "Escuela de Ciencias Sociales",
        "activo": 1,
    },
    {
        "id": 12,
        "titulo": "Narrativas digitales para participacion ciudadana",
      "ano": "2025",
        "universidad": "Universidad Latina de Panama",
        "siglas": "ULAT",
        "resumen": "Estudio sobre plataformas de comunicacion civica y su efecto en la participacion de jovenes universitarios.",
        "categoria": "Ciencias Sociales y Humanisticas",
        "premio": "Tercer Lugar",
        "asesor": "Ivan Cardenas",
        "email": "ivan.cardenas@ulatina.edu.pa",
        "institucion": "Centro de Estudios Humanisticos",
        "activo": 1,
    },
    {
    "id": 13,
    "titulo": "Sistema de gestion de trafico inteligente",
    "ano": "2025",
    "universidad": "Universidad Tecnologica de Panama",
    "siglas": "UTP",
    "resumen": "Implementacion de semaforos inteligentes basados en flujo vehicular en tiempo real.",
    "categoria": "Ingenieria",
    "premio": "Participante",
    "asesor": "Andres Lopez",
    "email": "andres.lopez@utp.ac.pa",
    "institucion": "Facultad de Ingenieria Civil",
    "activo": 1
  },
  {
    "id": 14,
    "titulo": "Optimizacion de consumo energetico en edificios",
    "ano": "2024",
    "universidad": "Universidad de Panama",
    "siglas": "UP",
    "resumen": "Analisis de eficiencia energetica mediante simulaciones computacionales.",
    "categoria": "Ingenieria",
    "premio": "Participante",
    "asesor": "Lucia Torres",
    "email": "lucia.torres@up.ac.pa",
    "institucion": "Facultad de Arquitectura",
    "activo": 1
  },
  {
    "id": 15,
    "titulo": "Aplicacion movil para seguimiento de pacientes",
    "ano": "2025",
    "universidad": "Universidad Latina de Panama",
    "siglas": "ULAT",
    "resumen": "Desarrollo de app para monitoreo remoto de pacientes cronicos.",
    "categoria": "Ciencias de la Salud",
    "premio": "Participante",
    "asesor": "Elena Rios",
    "email": "elena.rios@ulatina.edu.pa",
    "institucion": "Facultad de Ciencias de la Salud",
    "activo": 1
  },
  {
    "id": 16,
    "titulo": "Estudio de habitos alimenticios en universitarios",
    "ano": "2023",
    "universidad": "Universidad Catolica Santa Maria La Antigua",
    "siglas": "USMA",
    "resumen": "Analisis de patrones nutricionales y su relacion con rendimiento academico.",
    "categoria": "Ciencias de la Salud",
    "premio": "Participante",
    "asesor": "Miguel Sanchez",
    "email": "miguel.sanchez@usma.ac.pa",
    "institucion": "Departamento de Nutricion",
    "activo": 1
  },
  {
    "id": 17,
    "titulo": "Simulacion de cambio climatico regional",
    "ano": "2025",
    "universidad": "Universidad Maritima Internacional de Panama",
    "siglas": "UMIP",
    "resumen": "Modelo predictivo del impacto del cambio climatico en costas panamenas.",
    "categoria": "Ciencias Naturales y Exactas",
    "premio": "Participante",
    "asesor": "Ricardo Vega",
    "email": "ricardo.vega@umip.ac.pa",
    "institucion": "Centro de Investigacion Marina",
    "activo": 1
  },
  {
    "id": 18,
    "titulo": "Analisis de calidad del agua en rios urbanos",
    "ano": "2024",
    "universidad": "Universidad Interamericana de Panama",
    "siglas": "UIP",
    "resumen": "Evaluacion de contaminantes en fuentes hidricas urbanas.",
    "categoria": "Ciencias Naturales y Exactas",
    "premio": "Participante",
    "asesor": "Sofia Martinez",
    "email": "sofia.martinez@uip.edu.pa",
    "institucion": "Laboratorio Ambiental",
    "activo": 1
  },
  {
    "id": 19,
    "titulo": "Uso de redes sociales en educacion superior",
    "ano": "2025",
    "universidad": "Universidad Metropolitana de Educacion Ciencia y Tecnologia",
    "siglas": "UMECIT",
    "resumen": "Estudio del impacto de redes sociales en procesos de aprendizaje.",
    "categoria": "Ciencias Sociales y Humanisticas",
    "premio": "Participante",
    "asesor": "Daniel Gomez",
    "email": "daniel.gomez@umecit.edu.pa",
    "institucion": "Facultad de Educacion",
    "activo": 1
  },
  {
    "id": 20,
    "titulo": "Percepcion ciudadana sobre seguridad urbana",
    "ano": "2023",
    "universidad": "Universidad del Istmo",
    "siglas": "UDI",
    "resumen": "Encuesta sobre percepcion de seguridad en zonas metropolitanas.",
    "categoria": "Ciencias Sociales y Humanisticas",
    "premio": "Participante",
    "asesor": "Laura Mendez",
    "email": "laura.mendez@udi.edu.pa",
    "institucion": "Escuela de Sociologia",
    "activo": 1
  }
]


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/proyectos-jic")
def proyectos_jic() -> dict:
    return {
        "total": len(PROJECTS),
        "ganadores_historicos": PROJECTS,
    }
