# Generated by Django 5.2 on 2026-03-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=200, verbose_name='Premio')),
                ('year', models.CharField(max_length=10, verbose_name='Año')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['sort_order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='background_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, verbose_name='Año / Período')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='frequently_ask_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.SlugField(choices=[('participacion', 'Participación y Equipos'), ('plataforma', 'Plataforma Tecnológica'), ('entregables', 'Entregables y Evaluación')], default='participacion', help_text='Identificador interno de la categoría (ej: participacion, plataforma, entregables)', verbose_name='Slug de categoría')),
                ('category', models.CharField(choices=[('participacion', 'Participación y Equipos'), ('plataforma', 'Plataforma Tecnológica'), ('entregables', 'Entregables y Evaluación')], max_length=150, verbose_name='Categoría')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': [models.Case(models.When(category_slug='participacion', then=0), models.When(category_slug='plataforma', then=1), models.When(category_slug='entregables', then=2)), 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='important_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Fecha importante',
                'verbose_name_plural': 'Fechas importantes',
                'ordering': ['sort_order', 'event_date'],
            },
        ),
        migrations.CreateModel(
            name='jic_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría JIC',
                'verbose_name_plural': 'Categorías JIC',
                'ordering': ['sort_order'],
            },
        ),
    ]
