# Generated by Django 5.2 on 2026-03-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: JIC Nacional 2025', max_length=200, verbose_name='Título principal')),
                ('main_description', models.TextField(help_text='Descripción del evento y contexto', verbose_name='Descripción principal')),
                ('secondary_description', models.TextField(help_text='Información adicional o llamado a la acción', verbose_name='Descripción secundaria')),
                ('framework_label', models.CharField(default='En el marco de', help_text='Texto que precede al evento organizador', max_length=100, verbose_name='Etiqueta de marco')),
                ('framework_text', models.CharField(help_text='Ej: Congreso IESTEC 2025', max_length=200, verbose_name='Evento organizador')),
                ('logo_image', models.ImageField(blank=True, help_text='Logo a mostrar junto a la descripción', null=True, upload_to='event_logos/', verbose_name='Logo del evento')),
                ('logo_alt_text', models.CharField(default='Event Logo', help_text='Descripción accesible del logo', max_length=200, verbose_name='Texto alternativo del logo')),
                ('logo_fallback_text', models.CharField(default='EVENT', help_text='Texto a mostrar si la imagen no carga', max_length=50, verbose_name='Texto de respaldo para logo')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar esta sección', verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Intro del Evento',
                'verbose_name_plural': 'Intros del Evento',
                'ordering': ['sort_order'],
            },
        ),
    ]
