# Generated by Django 5.2 on 2026-03-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_event_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_intro',
            options={'verbose_name': 'Intro del Evento', 'verbose_name_plural': 'Intro del Evento'},
        ),
        migrations.RemoveField(
            model_name='event_intro',
            name='logo_alt_text',
        ),
        migrations.RemoveField(
            model_name='event_intro',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, help_text='Logo a mostrar junto a la descripción', null=True, upload_to='awards_logos/', verbose_name='Logo del evento'),
        ),
        migrations.AlterField(
            model_name='event_intro',
            name='framework_text',
            field=models.CharField(help_text='Ej: Congreso IESTEC', max_length=200, verbose_name='Evento organizador'),
        ),
        migrations.AlterField(
            model_name='event_intro',
            name='logo_fallback_text',
            field=models.CharField(default='Logo del evento', help_text='Texto a mostrar si la imagen no carga', max_length=50, verbose_name='Texto de respaldo para logo'),
        ),
        migrations.AlterField(
            model_name='event_intro',
            name='title',
            field=models.CharField(help_text='Ej: JIC Nacional', max_length=200, verbose_name='Título principal'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activar o desactivar esta pregunta', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='important_date',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activar o desactivar esta fecha', verbose_name='Activo'),
        ),
    ]
