# Generated by Django 5.2 on 2026-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_faq_initial_data'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='important_date',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=150, verbose_name='Título')),
                        ('event_date', models.DateField(verbose_name='Fecha del evento')),
                        ('description', models.TextField(verbose_name='Descripción')),
                        ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                        ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                    ],
                    options={
                        'verbose_name': 'Fecha importante',
                        'verbose_name_plural': 'Fechas importantes',
                        'ordering': ['sort_order', 'event_date'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "web_importantdate"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='ImportantDate'),
            ],
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='answer',
            field=models.TextField(verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category',
            field=models.CharField(max_length=150, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category_slug',
            field=models.SlugField(choices=[('participacion', 'Participación'), ('plataforma', 'Plataforma'), ('entregables', 'Entregables')], default='entregables', help_text='Identificador interno de la categoría (ej: participacion, plataforma, entregables)', verbose_name='Slug de categoría'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='question',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
