# Generated by Django 5.2 on 2026-03-12 02:42

import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_event_intro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_short_name', models.CharField(max_length=20, verbose_name='Sigla Universidad')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Coordinador')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('photo', models.ImageField(blank=True, help_text='Foto de perfil del coordinador', null=True, upload_to='coordinators_photos/', verbose_name='Foto del coordinador')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Coordinador Nacional',
                'verbose_name_plural': 'Coordinadores Nacionales',
                'ordering': ['sort_order'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='organizer_committee_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('role', models.CharField(max_length=200, verbose_name='Rol/Posición')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('photo', models.ImageField(blank=True, help_text='Foto de perfil del miembro del comité', null=True, upload_to='organizer_photos/', verbose_name='Foto del miembro')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Miembro del Comité Organizador',
                'verbose_name_plural': 'Miembros del Comité Organizador',
                'ordering': ['sort_order'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
