# Generated by Django 5.2 on 2026-03-12 03:32

import django.db.models.deletion
import modelcluster.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_coordinator_organizer_committee_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='selection_institutional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=300, verbose_name='Universidad')),
                ('short_name', models.CharField(max_length=20, verbose_name='Sigla')),
                ('year', models.PositiveIntegerField(verbose_name='Año JIC')),
                ('status', models.CharField(choices=[('completada', 'Completada'), ('en_proceso', 'En proceso'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, esta universidad no aparecerá en la página. Si todas están desactivadas, la página redirige a Resultados.', verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Selección Institucional',
                'verbose_name_plural': 'Selecciones Institucionales',
                'ordering': ['sort_order', 'university'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='selection_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Etiqueta')),
                ('href', models.URLField(help_text='URL pública del documento', verbose_name='Enlace')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.selection_institutional')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='selection_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='Categoría')),
                ('selected', models.PositiveIntegerField(verbose_name='Seleccionados')),
                ('total', models.PositiveIntegerField(verbose_name='Total presentados')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web.selection_institutional')),
            ],
            options={
                'verbose_name': 'Resultado por categoría',
                'verbose_name_plural': 'Resultados por categoría',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
