# Generated by Django 5.2 on 2026-03-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_important_date_delete_importantdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category_slug',
            field=models.SlugField(choices=[('participacion', 'Participación'), ('plataforma', 'Plataforma'), ('entregables', 'Entregables')], default='entregables', error_messages={'invalid_choice': 'Por favor, selecciona una categoría válida: Participación, Plataforma o Entregables.'}, help_text='Identificador interno de la categoría (ej: participacion, plataforma, entregables)', verbose_name='Slug de categoría'),
        ),
    ]
