# Generated by Django 5.2 on 2026-03-12 19:31

import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_seleccion_institucional_seleccion_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('video_file', models.FileField(help_text='Formatos soportados: MP4, WebM, Ogg (máx 500MB)', upload_to='videos/', verbose_name='Archivo de video')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagen de previsualización para el video', null=True, upload_to='video_thumbnails/', verbose_name='Miniatura')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duración total del video en segundos', null=True, verbose_name='Duración (segundos)')),
                ('category', models.CharField(blank=True, help_text='Ej: Tutorial, Presentación, Promocional', max_length=100, verbose_name='Categoría')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar este video', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['sort_order', '-created_at'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
