# Generated by Django 5.2 on 2026-03-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_frequently_ask_question_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category_slug',
            field=models.SlugField(choices=[('participacion', 'Participación'), ('plataforma', 'Plataforma'), ('entregables', 'Entregables')], default='participacion', help_text='Identificador interno de la categoría (ej: participacion, plataforma, entregables)', verbose_name='Slug de categoría'),
        ),
    ]
