# Generated by Django 5.2 on 2026-03-12 20:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.models.preview
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('doc_type', models.CharField(choices=[('lineamientos', 'Lineamientos'), ('plantillas', 'Plantillas'), ('memorias', 'Memorias'), ('boletines', 'Boletines'), ('actas', 'Actas de Resultados'), ('otros', 'Otros')], default='otros', help_text='Clasificación del documento', max_length=50, verbose_name='Tipo de documento')),
                ('document_file', models.FileField(help_text='Formatos soportados: PDF, DOCX, XLS, etc.', upload_to=web.models.get_document_path, verbose_name='Archivo')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Año al que corresponde el documento (ej: 2025, 2024)', null=True, verbose_name='Año JIC')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar este documento', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Documento de Recurso',
                'verbose_name_plural': 'Documentos de Recursos',
                'ordering': ['doc_type', '-year', 'sort_order'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='selection_document',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.selection_institutional'),
        ),
        migrations.AlterField(
            model_name='selection_result',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web.selection_institutional'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen de previsualización para el video', null=True, upload_to=web.models.get_video_thumbnail_path, verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(help_text='Formatos soportados: MP4, WebM, Ogg (máx 500MB)', upload_to=web.models.get_video_file_path, verbose_name='Archivo de video'),
        ),
    ]
