# Generated by Django 5.2 on 2026-03-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_frequently_ask_question_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequently_ask_question',
            options={'ordering': [models.Case(models.When(category_slug='participacion', then=0), models.When(category_slug='plataforma', then=1), models.When(category_slug='entregables', then=2)), 'sort_order'], 'verbose_name': 'Pregunta frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category_slug',
            field=models.SlugField(choices=[('participacion', 'Participación y Equipos'), ('plataforma', 'Plataforma Tecnológica'), ('entregables', 'Entregables y Evaluación')], default='participacion', help_text='Identificador interno de la categoría (ej: participacion, plataforma, entregables)', verbose_name='Slug de categoría'),
        ),
    ]
