# Generated by Django 5.2 on 2026-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_frequently_ask_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=200, verbose_name='Premio')),
                ('year', models.CharField(max_length=10, verbose_name='Año')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['sort_order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='background_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, verbose_name='Año / Período')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='jic_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría JIC',
                'verbose_name_plural': 'Categorías JIC',
                'ordering': ['sort_order'],
            },
        ),
    ]
