# Generated by Django 5.2 on 2026-03-13 02:42

from django.db import migrations


def add_sample_videos(apps, schema_editor):
    """Add sample videos to the database for testing"""
    video = apps.get_model('web', 'video')
    
    videos = [
        {
            'title': 'Video promocional JIC Nacional',
            'description': 'Conoce la JIC Nacional, el evento de investigacion mas importante para jovenes en Panama.',
            'video_file': '',
            'category': 'Promocional',
            'sort_order': 1,
        },
        {
            'title': '¿Cómo preparar tu proyecto de investigación?',
            'description': 'Tutorial sobre cómo preparar y presentar un proyecto de investigación en la JIC.',
            'video_file': '',
            'category': 'Tutorial',
            'sort_order': 2,
        },
        {
            'title': 'Guía de Investigación Científica',
            'description': 'Tutorial completo sobre metodología y pasos para realizar investigación científica.',
            'video_file': '',
            'category': 'Educativo',
            'sort_order': 3,
        },
        {
            'title': 'Inducción a la JIC 2024',
            'description': 'Recursos sobre cómo presentar tu proyecto en la JIC 2024.',
            'video_file': '',
            'category': 'Inducción',
            'sort_order': 4,
        },
        {
            'title': 'Video de Prueba Interno',
            'description': 'Video de prueba para verificar el reproductor de videos internos.',
            'video_file': '',
            'category': 'Prueba',
            'sort_order': 5,
        },
    ]
    
    for video_data in videos:
        # Solo crear si no existe
        if not video.objects.filter(title=video_data['title']).exists():
            video.objects.create(
                title=video_data['title'],
                description=video_data['description'],
                video_file=video_data['video_file'],
                category=video_data['category'],
                sort_order=video_data['sort_order'],
                is_active=True,
            )


def remove_sample_videos(apps, schema_editor):
    """Remove sample videos if rollback is needed"""
    video = apps.get_model('web', 'video')
    video.objects.filter(category__in=['Promocional', 'Tutorial', 'Educativo', 'Inducción', 'Prueba']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_resource_document_alter_selection_document_parent_and_more'),
    ]

    operations = [
        migrations.RunPython(add_sample_videos, remove_sample_videos),
    ]
