# Generated by Django 5.2 on 2026-03-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_add_sample_videos'),
    ]

    operations = [
    ]
