# Generated by Django 5.2 on 2026-03-13 03:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('web', '0010_alter_selection_result_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Galería Principal', max_length=150, verbose_name='Título de la galería')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la galería.', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Galería de Fotos',
                'verbose_name_plural': 'Galería de Fotos',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Categoría o texto alternativo', max_length=250, verbose_name='Categoría / Leyenda')),
                ('gallery', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='web.gallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
