# Generated by Django 5.2 on 2026-03-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
