# Generated by Django 5.2 on 2026-03-15 05:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('web', '0012_alter_galleryimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='title_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='JIC Nacional', help_text="Texto mostrado en la etiqueta superior (ej: 'JIC Nacional {year}')", max_length=200, verbose_name='Título/Subtítulo')),
                ('description', models.TextField(default='Fomentando la investigación entre jóvenes universitarios a nivel nacional.', help_text='Párrafo descriptivo principal', verbose_name='Descripción')),
                ('carousel_interval', models.PositiveIntegerField(default=8000, help_text='Milisegundos entre cambios automáticos (8000 = 8 segundos)', verbose_name='Intervalo del carrusel (ms)')),
                ('is_active', models.BooleanField(default=True, help_text='Mostrar u ocultar esta sección', verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Sección de Título/Hero',
                'verbose_name_plural': 'Secciones de Título/Hero',
                'ordering': ['sort_order'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='title_section_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta del botón')),
                ('url', models.CharField(help_text='URL externa (ej: https://...) o ruta de Django (ej: nombre_vista)', max_length=500, verbose_name='URL / Ruta')),
                ('button_type', models.CharField(choices=[('primary', 'Primario (Destacado)'), ('secondary', 'Secundario')], default='primary', max_length=20, verbose_name='Tipo de botón')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_buttons', to='web.title_section')),
            ],
            options={
                'verbose_name': 'Botón de acción',
                'verbose_name_plural': 'Botones de acción',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='title_section_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(help_text='Descripción para accesibilidad', max_length=300, verbose_name='Texto alternativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagen del carrusel')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='web.title_section')),
            ],
            options={
                'verbose_name': 'Imagen del carrusel',
                'verbose_name_plural': 'Imágenes del carrusel',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
