# Generated by Django 5.2 on 2026-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_title_section_title_section_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_section_image',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
