# Generated by Django 5.2 on 2026-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_title_section_image_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_section',
            name='description',
            field=models.TextField(default='Fomentando la investigación entre jóvenes universitarios a nivel nacional. Una iniciativa de la Secretaría Nacional de Ciencia, Tecnología e Innovación.', help_text='Párrafo descriptivo principal', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='title_section',
            name='title',
            field=models.CharField(default='JIC Nacional', editable=False, help_text="Texto mostrado en la etiqueta superior (ej: 'JIC Nacional {año}'), el año se calcula automáticamente y no debe incluirse aquí", max_length=200, verbose_name='Título/Subtítulo'),
        ),
    ]
