# Generated by Django 5.2 on 2026-03-15 19:02

import django.db.models.deletion
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_title_section_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Institución')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('abstract', models.TextField(verbose_name='Resumen')),
                ('university', models.CharField(max_length=255, verbose_name='Universidad')),
                ('category', models.CharField(max_length=255, verbose_name='Categoría')),
                ('winner', models.PositiveSmallIntegerField(choices=[(0, 'No ganador'), (1, 'Primer lugar'), (2, 'Segundo lugar'), (3, 'Tercer lugar')], default=0, verbose_name='Estado de Premio')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='web.consultant', verbose_name='Asesor')),
            ],
            options={
                'verbose_name': 'Investigación',
                'verbose_name_plural': 'Investigaciones',
                'ordering': ['-year', 'title'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
