# Generated by Django 5.2 on 2026-03-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_consultant_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='university_short_name',
            field=models.CharField(blank=True, help_text='Siglas de la Universidad', max_length=50, null=True, verbose_name='Siglas'),
        ),
    ]
