# Generated by Django 5.2 on 2026-03-17 01:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_project_university_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='selection_national',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Año JIC')),
                ('status', models.CharField(choices=[('completada', 'Completada'), ('en_proceso', 'En proceso'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total_projects', models.PositiveIntegerField(default=0, help_text='Para datos históricos, si no se usan los resultados por categoría.', verbose_name='Total de Proyectos (Histórico)')),
                ('host_university', models.CharField(blank=True, help_text='Universidad anfitriona del evento nacional (Opcional)', max_length=300, null=True, verbose_name='Universidad Sede')),
                ('universities_count', models.PositiveIntegerField(default=5, verbose_name='Universidades Participantes')),
                ('is_active', models.BooleanField(default=True, help_text='Activar para mostrar estos resultados nacionales en la página.', verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Selección Nacional',
                'verbose_name_plural': 'Selecciones Nacionales',
                'ordering': ['-year', 'sort_order'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='event_intro',
            options={'verbose_name': 'Introducción del Evento', 'verbose_name_plural': 'Introducción del Evento'},
        ),
        migrations.AlterModelOptions(
            name='resource_document',
            options={'ordering': ['-year', 'doc_type', 'sort_order'], 'verbose_name': 'Documento de Recurso', 'verbose_name_plural': 'Documentos de Recursos'},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texto alternativo para lectores de pantalla', max_length=255, verbose_name='Leyenda / Accesibilidad'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, help_text='Año de la edición (Ej: 2024)', max_length=100, verbose_name='Año / Edición'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción visible de la imagen', verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='selection_national_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Etiqueta')),
                ('document_type', models.CharField(default='PDF', max_length=50, verbose_name='Tipo (ej: PDF, XLS)')),
                ('href', models.URLField(help_text='URL pública del documento', verbose_name='Enlace')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.selection_national')),
            ],
            options={
                'verbose_name': 'Documento Nacional',
                'verbose_name_plural': 'Documentos Nacionales',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='selection_national_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ingenieria', 'Ingeniería'), ('ciencias_de_la_salud', 'Ciencias de la Salud'), ('ciencias_naturales_y_exactas', 'Ciencias Naturales y Exactas'), ('ciencias_sociales_y_humanisticas', 'Ciencias Sociales y Humanísticas')], max_length=150, verbose_name='Categoría')),
                ('participating_projects', models.PositiveIntegerField(verbose_name='Proyectos Participantes')),
                ('winners', models.PositiveIntegerField(verbose_name='Ganadores')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web.selection_national')),
            ],
            options={
                'verbose_name': 'Resultado Nacional por categoría',
                'verbose_name_plural': 'Resultados Nacionales por categoría',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
