# Generated by Django 5.2 on 2026-03-17 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_selection_national_alter_event_intro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_intro',
            name='logo_image',
            field=models.FileField(blank=True, help_text='Logo a mostrar junto a la descripción (Se aceptan PNG, JPG, SVG)', null=True, upload_to='event_logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Logo del evento'),
        ),
    ]
