# Generated by Django 5.2 on 2026-03-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_event_intro_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='important_date',
            name='date_text',
            field=models.CharField(blank=True, help_text="Ej: 'Del 04 de mayo al 31 de agosto' o 'Hasta el 15 de septiembre'.", max_length=200, verbose_name='Texto de la fecha'),
        ),
        migrations.AlterField(
            model_name='important_date',
            name='event_date',
            field=models.DateField(help_text='Fecha base usada internamente para ordenar cronológicamente.', verbose_name='Fecha para ordenar'),
        ),
    ]
