# Generated by Django 5.2 on 2026-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_important_date_date_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='important_date',
            name='title',
            field=models.CharField(default='Selección Nacional', max_length=150, verbose_name='Título'),
        ),
    ]
