# Generated by Django 5.2 on 2026-03-19 03:19

import web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_important_date_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Ej: https://www.youtube.com/watch?v=oispNb8t79o', verbose_name='Enlace de YouTube'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Formatos soportados: MP4, WebM, Ogg (máx 500MB). Deja en blanco si usas YouTube.', null=True, upload_to=web.utils.get_video_file_path, verbose_name='Archivo de video'),
        ),
    ]
