# Generated by Django 5.2 on 2026-03-19 21:07

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
        ('web', '0022_video_youtube_url_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Introducción')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('excerpt', models.TextField(blank=True, max_length=320, verbose_name='Resumen')),
                ('author_name', models.CharField(blank=True, max_length=120, verbose_name='Autor')),
                ('is_external_submission', models.BooleanField(default=False, help_text='Marcar cuando la nota fue enviada por un colaborador externo.', verbose_name='Envío externo')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'label': 'Párrafo'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Cita'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Contenido embebido'})}, verbose_name='Contenido')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
            bases=('wagtailcore.page',),
        ),
    ]
