# Generated by Django 5.2 on 2026-03-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_sync_imagefields_to_wagtail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
