# Generated by Django 5.2 on 2026-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_seed_current_results_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection_national',
            name='host_university',
        ),
        migrations.AddField(
            model_name='selection_national',
            name='host_place',
            field=models.CharField(blank=True, help_text='Lugar donde se lleva a cabo el evento nacional (Opcional)', max_length=300, null=True, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='selection_national',
            name='status',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en proceso', 'En proceso')], default='en proceso', max_length=20, verbose_name='Estado'),
        ),
    ]
