# Generated by Django 5.2 on 2026-03-22 22:58

import django.db.models.deletion
import taggit.managers
import wagtail.images.models
import wagtail.models.media
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


def copy_wagtail_images_to_custom(apps, schema_editor):
    WagtailImage = apps.get_model('wagtailimages', 'Image')
    WagtailRendition = apps.get_model('wagtailimages', 'Rendition')
    CustomImage = apps.get_model('web', 'CustomImage')
    CustomRendition = apps.get_model('web', 'CustomRendition')

    existing_custom_ids = set(CustomImage.objects.values_list('id', flat=True))
    images_to_create = []

    for img in WagtailImage.objects.all().iterator():
        if img.id in existing_custom_ids:
            continue
        images_to_create.append(
            CustomImage(
                id=img.id,
                title=img.title,
                file=img.file,
                description=img.description,
                width=img.width,
                height=img.height,
                created_at=img.created_at,
                focal_point_x=img.focal_point_x,
                focal_point_y=img.focal_point_y,
                focal_point_width=img.focal_point_width,
                focal_point_height=img.focal_point_height,
                file_size=img.file_size,
                file_hash=img.file_hash,
                collection_id=img.collection_id,
                uploaded_by_user_id=img.uploaded_by_user_id,
            )
        )

    if images_to_create:
        CustomImage.objects.bulk_create(images_to_create)

    existing_rendition_ids = set(CustomRendition.objects.values_list('id', flat=True))
    existing_image_ids = set(CustomImage.objects.values_list('id', flat=True))
    renditions_to_create = []

    for r in WagtailRendition.objects.all().iterator():
        if r.id in existing_rendition_ids:
            continue
        if r.image_id not in existing_image_ids:
            continue
        renditions_to_create.append(
            CustomRendition(
                id=r.id,
                filter_spec=r.filter_spec,
                file=r.file,
                width=r.width,
                height=r.height,
                focal_point_key=r.focal_point_key,
                image_id=r.image_id,
            )
        )

    if renditions_to_create:
        CustomRendition.objects.bulk_create(renditions_to_create)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('web', '0030_remove_selection_national_host_university_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.images.models.ImageFileMixin, wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CustomRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='web.customimage')),
            ],
            options={
                'unique_together': {('image', 'filter_spec', 'focal_point_key')},
            },
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
        migrations.RunPython(copy_wagtail_images_to_custom, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name='blogpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.customimage', verbose_name='Imagen destacada'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.customimage', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='title_section_image',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.customimage', verbose_name='Imagen del carrusel'),
        ),
    ]
