# Generated by Django 5.2 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_customimage_alter_blogpage_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="is_visible_in_resources",
            field=models.BooleanField(
                default=True,
                help_text="Activa o desactiva esta imagen en la pestaña Galería de la sección Recursos",
                verbose_name="Visible en Recursos",
            ),
        ),
    ]
