# Generated by Django 5.2 on 2026-03-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_galleryimage_is_visible_in_resources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryimage",
            name="is_visible_in_resources",
        ),
        migrations.CreateModel(
            name="CollectionResourceVisibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_visible_in_resources",
                    models.BooleanField(
                        default=True,
                        help_text="Controla si esta colección de Wagtail aparece en la pestaña Galería de Recursos.",
                        verbose_name="Visible en galería de Recursos",
                    ),
                ),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_visibility",
                        to="wagtailcore.collection",
                        verbose_name="Colección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visibilidad de colección en Recursos",
                "verbose_name_plural": "Visibilidad de colecciones en Recursos",
            },
        ),
    ]
