# Generated by Django 5.2 on 2026-03-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_gallery_collection_visibility_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customimage',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterField(
            model_name='selection_national',
            name='status',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_proceso', 'En proceso')], default='en_proceso', max_length=20, verbose_name='Estado'),
        ),
    ]
