# Generated by Django 5.2 on 2026-03-24 22:57

import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_customimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='national_coordinators_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Coordinadores Nacionales', help_text='Título que se muestra en la sección', max_length=200, verbose_name='Título de la sección')),
                ('description', models.TextField(default='Representantes de cada universidad participante en la JIC.', help_text='Descripción breve de la sección', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Activar o desactivar la sección completa de Coordinadores Nacionales', verbose_name='Mostrar sección')),
            ],
            options={
                'verbose_name': 'Sección de Coordinadores Nacionales',
                'verbose_name_plural': 'Sección de Coordinadores Nacionales',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
