# Generated by Django 5.2 on 2026-03-25

from django.db import migrations, models, transaction
from django.db.models.functions import Lower


def _dedupe_consultants(apps, schema_editor):
    Consultant = apps.get_model("web", "consultant")
    Project = apps.get_model("web", "project")

    seen = {}
    replacements = {}

    for c in Consultant.objects.all().order_by("id").only("id", "name"):
        key = (c.name or "").strip().lower()
        if not key:
            continue
        if key not in seen:
            seen[key] = c.id
            continue
        replacements[c.id] = seen[key]

    if not replacements:
        return

    for old_id, new_id in replacements.items():
        Project.objects.filter(advisor_id=old_id).update(advisor_id=new_id)

    Consultant.objects.filter(id__in=list(replacements.keys())).delete()


def _dedupe_projects(apps, schema_editor):
    Project = apps.get_model("web", "project")

    seen = {}

    for p in Project.objects.all().order_by("id"):
        key = ((p.title or "").strip().lower(), int(p.year or 0))
        if not key[0] or not key[1]:
            continue

        keep_id = seen.get(key)
        if keep_id is None:
            seen[key] = p.id
            continue

        keep = Project.objects.get(id=keep_id)
        changed_fields = []

        if (not keep.abstract) and p.abstract:
            keep.abstract = p.abstract
            changed_fields.append("abstract")
        if (keep.advisor_id is None) and p.advisor_id is not None:
            keep.advisor_id = p.advisor_id
            changed_fields.append("advisor")
        if (not keep.university) and p.university:
            keep.university = p.university
            changed_fields.append("university")
        if (not keep.university_short_name) and p.university_short_name:
            keep.university_short_name = p.university_short_name
            changed_fields.append("university_short_name")
        if (not keep.category) and p.category:
            keep.category = p.category
            changed_fields.append("category")
        if int(keep.winner or 0) == 0 and int(p.winner or 0) > 0:
            keep.winner = p.winner
            changed_fields.append("winner")

        if changed_fields:
            keep.save(update_fields=changed_fields)

        p.delete()


def _dedupe_existing_rows(apps, schema_editor):
    with transaction.atomic():
        _dedupe_consultants(apps, schema_editor)
        _dedupe_projects(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0035_national_coordinators_section"),
    ]

    operations = [
        migrations.RunPython(_dedupe_existing_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="consultant",
            constraint=models.UniqueConstraint(
                Lower("name"),
                name="web_consultant_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                Lower("title"),
                models.F("year"),
                name="web_project_title_year_ci_unique",
            ),
        ),
    ]
