# Generated by Django 5.2 on 2026-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_case_insensitive_uniqueness_projects_consultants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='photo',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='college_logo',
            field=models.ImageField(blank=True, help_text='Logo de la Universidad', null=True, upload_to='university_logos/', verbose_name='Logo de la Universidad'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='url',
            field=models.URLField(blank=True, help_text='URL opcional de la Universidad', verbose_name='Sitio web de la Universidad'),
        ),
    ]
