# Generated by Django 5.2 on 2026-03-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_normalize_faq_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_intro',
            name='framework_label',
            field=models.CharField(blank=True, default='En el marco de', help_text='Texto que precede al evento organizador', max_length=100, verbose_name='Etiqueta de marco'),
        ),
        migrations.AlterField(
            model_name='event_intro',
            name='framework_text',
            field=models.CharField(blank=True, help_text='Ej: Congreso IESTEC', max_length=200, verbose_name='Evento organizador'),
        ),
        migrations.AlterField(
            model_name='event_intro',
            name='logo_fallback_text',
            field=models.CharField(blank=True, default='Logo del evento', help_text='Texto a mostrar si la imagen no carga', max_length=50, verbose_name='Texto de respaldo para logo'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category',
            field=models.CharField(choices=[('participacion', 'Participación y Equipos'), ('plataforma', 'Plataforma Tecnológica'), ('entregables', 'Entregables y Evaluación')], help_text='La etiqueta se sincroniza automáticamente con la categoría seleccionada', max_length=150, verbose_name='Etiqueta de categoría'),
        ),
        migrations.AlterField(
            model_name='frequently_ask_question',
            name='category_slug',
            field=models.SlugField(choices=[('participacion', 'Participación y Equipos'), ('plataforma', 'Plataforma Tecnológica'), ('entregables', 'Entregables y Evaluación')], default='participacion', help_text='Selecciona la categoría para esta pregunta', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='title_section',
            name='title',
            field=models.CharField(default='JIC Nacional', help_text="Texto mostrado en la etiqueta superior (ej: 'JIC Nacional {año}'), el año se calcula automáticamente y no debe incluirse aquí", max_length=200, verbose_name='Título/Subtítulo'),
        ),
    ]
