# Generated by Django 5.2 on 2026-03-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0040_remove_selection_institutional_status_alter_selection_document"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selection_institutional",
            options={
                "ordering": ["sort_order", "-year", "university"],
                "verbose_name": "Selección Institucional",
                "verbose_name_plural": "Selecciones Institucionales",
            },
        ),
    ]
