# Generated by Django 6.0.5 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0044_normalize_project_categories_universities"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Año para ordenar y filtrar en la galería (ej: 2024).",
                null=True,
                verbose_name="Año",
            ),
        ),
        migrations.AddField(
            model_name="jic_category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Imagen opcional para representar visualmente la categoría.",
                null=True,
                upload_to="category_icons/",
                verbose_name="Ícono",
            ),
        ),
        migrations.CreateModel(
            name="site_content_settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_url",
                    models.URLField(
                        default="https://jic.utp.ac.pa",
                        help_text="Enlace usado por los botones y accesos de Plataforma JIC.",
                        verbose_name="URL de Plataforma JIC",
                    ),
                ),
                (
                    "quick_section_title",
                    models.CharField(
                        default="Accesos rápidos",
                        max_length=120,
                        verbose_name="Título de accesos rápidos",
                    ),
                ),
                (
                    "quick_section_description",
                    models.CharField(
                        default="Todo lo que necesitas para la JIC en un solo lugar",
                        max_length=240,
                        verbose_name="Descripción de accesos rápidos",
                    ),
                ),
                (
                    "faq_section_title",
                    models.CharField(
                        default="Preguntas Frecuentes",
                        max_length=120,
                        verbose_name="Título de preguntas frecuentes",
                    ),
                ),
                (
                    "faq_section_description",
                    models.CharField(
                        default="Todo lo que necesitas saber sobre la Jornada de Iniciación Científica",
                        max_length=240,
                        verbose_name="Descripción de preguntas frecuentes",
                    ),
                ),
                (
                    "ridda_url",
                    models.URLField(
                        default="https://ridda2.utp.ac.pa",
                        help_text="Enlace por defecto para referencias al repositorio institucional.",
                        verbose_name="URL de RIDDA",
                    ),
                ),
                (
                    "categories_reference_url",
                    models.URLField(
                        default="https://ridda2.utp.ac.pa",
                        help_text="Enlace alternativo cuando no exista documento etiquetado para categorías.",
                        verbose_name="URL de referencia para categorías",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Contenido del Sitio",
                "verbose_name_plural": "Configuración de Contenido del Sitio",
            },
        ),
    ]
