# Generated by Django 6.0.5 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0045_site_content_settings_and_gallery_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "ordering": [
                    models.OrderBy(models.F("year"), descending=True, nulls_last=True),
                    models.OrderBy(models.F("image__created_at"), descending=True, nulls_last=True),
                    "-pk",
                ],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
    ]
