# Generated by Django 6.0.5 on 2026-04-15

from django.db import migrations, models
import django.db.models.deletion


def backfill_galleryimage_collection(apps, schema_editor):
    GalleryImage = apps.get_model("web", "GalleryImage")

    for item in GalleryImage.objects.select_related("image").all():
        image_obj = getattr(item, "image", None)
        image_collection_id = getattr(image_obj, "collection_id", None)
        if item.collection_id is None and image_collection_id is not None:
            item.collection_id = image_collection_id
            item.save(update_fields=["collection"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0046_alter_galleryimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: mover la imagen a una colección específica al guardar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
                verbose_name="Colección",
            ),
        ),
        migrations.RunPython(backfill_galleryimage_collection, noop_reverse),
    ]
