# Generated by Django 6.0.5 on 2026-04-15

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("web", "0046_alter_galleryimage_options"),
    ]

    dependencies = [
        ("web", "0047_site_content_settings_and_gallery_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "ordering": ["sort_order", "-pk"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
    ]
