# Generated by Django 6.0.5 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0049_galleryimage_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                help_text="Se normaliza automáticamente a nombres canónicos (Ingeniería, Ciencias de la Salud, etc.)",
                max_length=255,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="university",
            field=models.CharField(
                help_text="Se normaliza automáticamente a nombres canónicos (mayúsculas, acentos, etc.)",
                max_length=255,
                verbose_name="Universidad",
            ),
        ),
        migrations.AlterField(
            model_name="selection_document",
            name="label",
            field=models.CharField(
                help_text="Nombre con que se muestra el documento",
                max_length=200,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="selection_national_document",
            name="label",
            field=models.CharField(
                help_text="Nombre con que se muestra el documento",
                max_length=200,
                verbose_name="Nombre",
            ),
        ),
    ]
