""" 
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
from pathlib import Path
from theme.tailwind_watcher import run_tailwind_watch


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-0$hb3)ta6z_952&)u2#zwc)kschwkjf2tmfksd=a^vg4gz^4jj")

# SECURITY WARNING: define the correct hosts in production!
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",")

# Start TailwindCSS watcher only in DEBUG mode and only for the autoreload main process.
DEBUG = env_bool("DEBUG", True)
if DEBUG and env_bool("TAILWIND_WATCH", True) and os.getenv("RUN_MAIN") == "true":
    run_tailwind_watch()
    

# Application definition

INSTALLED_APPS = [
    "theme",
    "web",
    "home",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'compressor',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "mysite.context_processors.debug",
                "mysite.context_processors.nav_items",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use local PostgreSQL database (jicweb_master) - load from container environment
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRESQL_DATABASE"),
        "USER": os.getenv("POSTGRESQL_POSTGRES_USERNAME"),
        "PASSWORD": os.getenv("POSTGRESQL_POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRESQL_HOST"),
        "PORT": os.getenv("POSTGRESQL_DATABASE_PORT_NUMBER"),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

COMPRESS_ROOT = PROJECT_DIR / 'theme/static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

STATICFILES_DIRS = []

STATIC_ROOT = BASE_DIR / "/app/staticfiles"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# MinIO Object Storage
MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "jic_minio_storage:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", "mast_st_jic")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", "KtWzuaY3Uy8F")
MINIO_USE_SSL = os.getenv("MINIO_USE_SSL", "false").lower() == "true"
MINIO_BUCKET_NAME = os.getenv("MINIO_BUCKET_NAME", "jic-media")
MINIO_EXTERNAL_URL = os.getenv("MINIO_EXTERNAL_URL", "http://localhost:9010")

# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "mysite.storage.MinioStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Allow larger uploads so originals can be compressed after upload.
FILE_UPLOAD_MAX_MEMORY_SIZE = 1000 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 1000 * 1024 * 1024


# Wagtail settings

WAGTAIL_SITE_NAME = "Jic Site"

# Wagtail theme
WAGTAIL_ADMIN_THEME = "light"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# External projects API
JIC_PROJECTS_API_URL = os.getenv("JIC_PROJECTS_API_URL", "http://127.0.0.1:8001/api/proyectos-jic")
JIC_PROJECTS_API_TIMEOUT = int(os.getenv("JIC_PROJECTS_API_TIMEOUT", "3"))
JIC_PROJECTS_CACHE_TTL = int(os.getenv("JIC_PROJECTS_CACHE_TTL", "300"))
JIC_PROJECTS_RETRY_AFTER_ERROR = int(os.getenv("JIC_PROJECTS_RETRY_AFTER_ERROR", "60"))
JIC_PROJECTS_AUTO_SYNC_DB = os.getenv("JIC_PROJECTS_AUTO_SYNC_DB", "1").lower() in {"1", "true", "yes", "on"}
JIC_PROJECTS_PREFER_API = os.getenv("JIC_PROJECTS_PREFER_API", "0").lower() in {"1", "true", "yes", "on"}

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Custom document model to add additional metadata fields.
WAGTAILDOCS_DOCUMENT_MODEL = "web.Document"
# Use custom document form to validate file size
WAGTAILDOCS_DOCUMENT_FORM_BASE = "web.forms.image_forms.DocumentAdminForm"

# Allowed file extensions for videos
# Supported video formats: MP4, WebM, Ogg
WAGTAIL_VIDEO_EXTENSIONS = ['mp4', 'webm', 'ogg', 'mov', 'avi']

# Disable Gravatar to disable the use of remote avatars
WAGTAIL_GRAVATAR_PROVIDER_URL = None

# Use inherited image admin form to customize tags help text and validate file size
WAGTAILIMAGES_IMAGE_FORM_BASE = "web.forms.image_forms.ImageAdminForm"
# Custom image and rendition models to implement custom compression.
WAGTAILIMAGES_IMAGE_MODEL = "web.CustomImage"
WAGTAILIMAGES_RENDITION_MODEL = "web.CustomRendition"

IMAGE_MAX_SOURCE_SIZE = 10 * 1024 * 1024
IMAGE_MAX_FINAL_SIZE = 5 * 1024 * 1024
WAGTAILIMAGES_MAX_UPLOAD_SIZE = IMAGE_MAX_SOURCE_SIZE
WAGTAILIMAGES_JPEG_QUALITY = 85
WAGTAILIMAGES_WEBP_QUALITY = 85

# Compression behavior shared by all uploaded raster images.
IMAGE_COMPRESSION_MAX_DIMENSION = 2560
IMAGE_COMPRESSION_QUALITY_STEPS = (86, 80, 74, 68, 62, 56, 50, 44)
IMAGE_COMPRESSION_SCALE_STEPS = (1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4)
IMAGE_COMPRESSION_CONVERT_PNG_TO_WEBP = True

WAGTAILADMIN_PERMITTED_LANGUAGES = [('en', 'English'), ('es', 'Spanish'),]