/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./**/templates/**/*.html",
  ],
  safelist: [
    "bg-primary/90",
    "text-primary-foreground",
    "bg-secondary-foreground/65",
    "bg-amber-400",
    "text-secondary-foreground",
    "bg-sky-100",
    "text-sky-700",
    "bg-violet-100",
    "text-violet-700",
    "bg-emerald-100",
    "text-emerald-600",
    "bg-amber-100",
    "text-amber-700",
    "border-sky-700",
    "border-violet-700",
    "border-emerald-600",
    "border-amber-700",
    "border-sky-300",
    "text-sky-300",
    "border-violet-300",
    "text-violet-300",
    "border-violet-400",
    "text-violet-400",
  ],
}
